/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockSymbolRouteImport } from './routes/stock.$symbol'
import { Route as OnboardingDifficultyRouteImport } from './routes/onboarding.difficulty'
import { Route as InvestThemesRouteImport } from './routes/invest.themes'
import { Route as InvestLargestCapRouteImport } from './routes/invest.largest-cap'
import { Route as InvestThemeThemeIdRouteImport } from './routes/invest.theme.$themeId'
import { Route as InvestMoversKindRouteImport } from './routes/invest.movers.$kind'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDifficultyRoute = OnboardingDifficultyRouteImport.update({
  id: '/onboarding/difficulty',
  path: '/onboarding/difficulty',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestThemesRoute = InvestThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => InvestRoute,
} as any)
const InvestLargestCapRoute = InvestLargestCapRouteImport.update({
  id: '/largest-cap',
  path: '/largest-cap',
  getParentRoute: () => InvestRoute,
} as any)
const InvestThemeThemeIdRoute = InvestThemeThemeIdRouteImport.update({
  id: '/theme/$themeId',
  path: '/theme/$themeId',
  getParentRoute: () => InvestRoute,
} as any)
const InvestMoversKindRoute = InvestMoversKindRouteImport.update({
  id: '/movers/$kind',
  path: '/movers/$kind',
  getParentRoute: () => InvestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/discover': typeof DiscoverRoute
  '/discussion': typeof DiscussionRoute
  '/help': typeof HelpRoute
  '/invest': typeof InvestRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/invest/largest-cap': typeof InvestLargestCapRoute
  '/invest/themes': typeof InvestThemesRoute
  '/onboarding/difficulty': typeof OnboardingDifficultyRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/invest/movers/$kind': typeof InvestMoversKindRoute
  '/invest/theme/$themeId': typeof InvestThemeThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/discover': typeof DiscoverRoute
  '/discussion': typeof DiscussionRoute
  '/help': typeof HelpRoute
  '/invest': typeof InvestRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/invest/largest-cap': typeof InvestLargestCapRoute
  '/invest/themes': typeof InvestThemesRoute
  '/onboarding/difficulty': typeof OnboardingDifficultyRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/invest/movers/$kind': typeof InvestMoversKindRoute
  '/invest/theme/$themeId': typeof InvestThemeThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/discover': typeof DiscoverRoute
  '/discussion': typeof DiscussionRoute
  '/help': typeof HelpRoute
  '/invest': typeof InvestRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/invest/largest-cap': typeof InvestLargestCapRoute
  '/invest/themes': typeof InvestThemesRoute
  '/onboarding/difficulty': typeof OnboardingDifficultyRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/invest/movers/$kind': typeof InvestMoversKindRoute
  '/invest/theme/$themeId': typeof InvestThemeThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/discover'
    | '/discussion'
    | '/help'
    | '/invest'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/more'
    | '/orders'
    | '/portfolio'
    | '/projects'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/invest/largest-cap'
    | '/invest/themes'
    | '/onboarding/difficulty'
    | '/stock/$symbol'
    | '/invest/movers/$kind'
    | '/invest/theme/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/discover'
    | '/discussion'
    | '/help'
    | '/invest'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/more'
    | '/orders'
    | '/portfolio'
    | '/projects'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/invest/largest-cap'
    | '/invest/themes'
    | '/onboarding/difficulty'
    | '/stock/$symbol'
    | '/invest/movers/$kind'
    | '/invest/theme/$themeId'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/discover'
    | '/discussion'
    | '/help'
    | '/invest'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/more'
    | '/orders'
    | '/portfolio'
    | '/projects'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/invest/largest-cap'
    | '/invest/themes'
    | '/onboarding/difficulty'
    | '/stock/$symbol'
    | '/invest/movers/$kind'
    | '/invest/theme/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DiscoverRoute: typeof DiscoverRoute
  DiscussionRoute: typeof DiscussionRoute
  HelpRoute: typeof HelpRoute
  InvestRoute: typeof InvestRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  OrdersRoute: typeof OrdersRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchlistRoute: typeof WatchlistRoute
  OnboardingDifficultyRoute: typeof OnboardingDifficultyRoute
  StockSymbolRoute: typeof StockSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/difficulty': {
      id: '/onboarding/difficulty'
      path: '/onboarding/difficulty'
      fullPath: '/onboarding/difficulty'
      preLoaderRoute: typeof OnboardingDifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/themes': {
      id: '/invest/themes'
      path: '/themes'
      fullPath: '/invest/themes'
      preLoaderRoute: typeof InvestThemesRouteImport
      parentRoute: typeof InvestRoute
    }
    '/invest/largest-cap': {
      id: '/invest/largest-cap'
      path: '/largest-cap'
      fullPath: '/invest/largest-cap'
      preLoaderRoute: typeof InvestLargestCapRouteImport
      parentRoute: typeof InvestRoute
    }
    '/invest/theme/$themeId': {
      id: '/invest/theme/$themeId'
      path: '/theme/$themeId'
      fullPath: '/invest/theme/$themeId'
      preLoaderRoute: typeof InvestThemeThemeIdRouteImport
      parentRoute: typeof InvestRoute
    }
    '/invest/movers/$kind': {
      id: '/invest/movers/$kind'
      path: '/movers/$kind'
      fullPath: '/invest/movers/$kind'
      preLoaderRoute: typeof InvestMoversKindRouteImport
      parentRoute: typeof InvestRoute
    }
  }
}

interface InvestRouteChildren {
  InvestLargestCapRoute: typeof InvestLargestCapRoute
  InvestThemesRoute: typeof InvestThemesRoute
  InvestMoversKindRoute: typeof InvestMoversKindRoute
  InvestThemeThemeIdRoute: typeof InvestThemeThemeIdRoute
}

const InvestRouteChildren: InvestRouteChildren = {
  InvestLargestCapRoute: InvestLargestCapRoute,
  InvestThemesRoute: InvestThemesRoute,
  InvestMoversKindRoute: InvestMoversKindRoute,
  InvestThemeThemeIdRoute: InvestThemeThemeIdRoute,
}

const InvestRouteWithChildren =
  InvestRoute._addFileChildren(InvestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DiscoverRoute: DiscoverRoute,
  DiscussionRoute: DiscussionRoute,
  HelpRoute: HelpRoute,
  InvestRoute: InvestRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  OrdersRoute: OrdersRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchlistRoute: WatchlistRoute,
  OnboardingDifficultyRoute: OnboardingDifficultyRoute,
  StockSymbolRoute: StockSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
