/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MoreRouteImport } from './routes/more'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as IndexRouteImport } from './routes/index'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/invest': typeof InvestRoute
  '/more': typeof MoreRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/invest': typeof InvestRoute
  '/more': typeof MoreRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discussion': typeof DiscussionRoute
  '/invest': typeof InvestRoute
  '/more': typeof MoreRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discussion' | '/invest' | '/more' | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discussion' | '/invest' | '/more' | '/portfolio'
  id: '__root__' | '/' | '/discussion' | '/invest' | '/more' | '/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscussionRoute: typeof DiscussionRoute
  InvestRoute: typeof InvestRoute
  MoreRoute: typeof MoreRoute
  PortfolioRoute: typeof PortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionRoute: DiscussionRoute,
  InvestRoute: InvestRoute,
  MoreRoute: MoreRoute,
  PortfolioRoute: PortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
